# Generated by Django 5.2.1 on 2025-05-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_car', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_car', models.CharField(max_length=50)),
                ('fechacreacion_car', models.DateField()),
                ('telefono_car', models.CharField(max_length=20)),
            ],
        ),
    ]
