# Generated by Django 5.2.1 on 2025-06-17 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Educacion', '0003_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='fk_id_car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Educacion.carrera'),
        ),
    ]
