# Generated by Django 5.2.1 on 2025-06-17 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Educacion', '0004_alter_curso_fk_id_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='fk_id_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Educacion.carrera'),
        ),
    ]
