# Generated by Django 5.2.3 on 2025-06-26 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Educacion', '0005_alter_curso_fk_id_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_mat', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_mat', models.CharField(max_length=60)),
                ('creditos_mat', models.IntegerField()),
                ('fk_id_cur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Educacion.curso')),
            ],
        ),
    ]
